name: "Node steps"
description: "Composite Github Action to provides opinionated NodeJS steps"
branding:
  icon: "hexagon"
  color: "green"

inputs:
  checkout-token:
    description: "Token used by checkout. See https://github.com/actions/checkout"
    default: ${{ github.token }}
  package-manager:
    description: "Used to specify a package manager. Supported values: 'yarn'"
    default: "yarn"
  build:
    description: Build parameters.
    default: "build"
  checks:
    description: "Optional flag to enable check steps."
  lint:
    description: "Optional flag to enable linting"
    default: true
  code-ql:
    description: "Code QL analysis language. See https://github.com/github/codeql-action"
    default: "typescript"
  test:
    description: "Optional flag to enable test. See https://github.com/github/codeql-action"
    default: true
  coverage:
    description: "Optional flag to enable coverage report. See https://github.com/codecov/codecov-action"
    default: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.checkout-token }}

    - uses: actions/setup-node@v2.5.1
      id: setup-node
      with:
        node-version-file: ".nvmrc"
        cache: ${{ inputs.package-manager }}
        cache-dependency-path: "**/yarn.lock"

    - name: ⚙️ Install Dependencies
      shell: bash
      run: yarn install --frozen-lockfile;

    - name: 👕 Lint
      if: inputs.checks == 'true' && inputs.lint == 'true'
      shell: bash
      run: yarn lint

    - name: 🛡️ CodeQL Analysis
      if: inputs.checks == 'true' && inputs.code-ql != 'false'
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ inputs.code-ql }}
    - uses: github/codeql-action/analyze@v1
      if: inputs.checks == 'true' && inputs.code-ql != 'false'

    - id: yarn-installed-packages
      if: inputs.build != 'false'
      shell: bash
      run: |
        echo ::set-output name=gatsby::$([[ `yarn list --pattern "gatsby" --depth=1 | grep " gatsby@"` ]] && echo "true" || echo "false")
        echo ::set-output name=storybook::$([[ `yarn list --pattern "storybook" --depth=1 | grep " @storybook/[-a-z]*@"` ]] && echo "true" || echo "false")

    - name: ♻️ Gatsby cache
      if: inputs.build != 'false' && steps.yarn-installed-packages.outputs.gatsby == 'true'
      uses: actions/cache@v2.1.7
      id: gatsby-cache
      with:
        path: |
          .cache
          public
        key: ${{ runner.os }}-cache-gatsby-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-gatsby-

    - name: ♻️ Storybook cache
      if: inputs.build != 'false' && steps.yarn-installed-packages.outputs.storybook == 'true'
      uses: actions/cache@v2.1.7
      id: storybook-cache
      with:
        path: node_modules/.cache/storybook
        key: ${{ runner.os }}-cache-storybook-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-cache-storybook-

    - id: prepare-build
      if: inputs.build != 'false'
      shell: bash
      run: |
        BUILD_INPUT=$(cat <<-END
            ${{ inputs.build }}
        END
        )
        BUILD_INPUT=$(echo $BUILD_INPUT | sed 's/ *$//g')

        if [ -z "$BUILD_INPUT" ]; then
            exit 0;
        fi

        # Pure string
        if echo "$BUILD_INPUT" | grep -c "^[_:a-zA-Z0-9]\+$" > /dev/null; then
            echo ::set-output name=env::{}

            BUILD_COMMAND=$( echo "\"$BUILD_INPUT\"" | jq '.' )
            if [ "$BUILD_COMMAND" == \""false\"" ]; then
              echo ::set-output name=command::
            else
              echo ::set-output name=command::$BUILD_COMMAND
            fi

            exit 0;
        fi

        CHECK_JSON=$( { echo "$BUILD_INPUT" | jq empty; } 2>&1 )
        if [ ! $? -eq 0 ] ; then
            echo -e "Given \"build\" input is not a valid JSON string: $CHECK_JSON.\n\"$BUILD_INPUT\""
            exit 1;
        fi

        # Build input is a JSON string
        if echo "$BUILD_INPUT" | jq 'type == "string"' | grep -c "true" > /dev/null; then

            BUILD_COMMAND=$( echo "$BUILD_INPUT" | jq '.' )
            echo ::set-output name=command::$BUILD_COMMAND
            echo ::set-output name=env::{}
            exit 0;

        fi

        # Build input is a JSON object
        if echo "$BUILD_INPUT" | jq 'type == "object"' | grep -c "true" > /dev/null; then

            BUILD_COMMAND=$( echo "$BUILD_INPUT" | jq ' . | if has("command") then .command else "build" end' )
            echo ::set-output name=command::$BUILD_COMMAND

            BUILD_ENV=$( echo "$BUILD_INPUT" | jq ' . | if has("env") then .env else {} end' )
            echo ::set-output name=env::$BUILD_ENV
            exit 0;

        fi

        echo -e "Given \"build\" input is not a string nor an object.\n$BUILD_INPUT"
        exit 1;

    - name: 🏗️ Build
      shell: bash
      if: inputs.build != 'false' && steps.prepare-build.outputs.command
      env: ${{ fromJSON(steps.prepare-build.outputs.env) }}
      run: yarn ${{ steps.prepare-build.outputs.command }}

    - name: ♻️ Get Jest cache dir
      if: inputs.checks == 'true' && inputs.test == 'true'
      id: jest-cache-dir-path
      shell: bash
      run: |
        JEST_CACHE_DIR=$(yarn jest --showConfig | grep -oP '(?<="cacheDirectory": ")[^"]+(?=")')
        echo "::set-output name=dir::$JEST_CACHE_DIR"

    - name: ♻️ Test cache
      if: inputs.checks == 'true' && inputs.test == 'true'
      uses: actions/cache@v2.1.7
      with:
        path: ${{ steps.jest-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-test-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-test-

    - name: 🧪 Test
      if: inputs.checks == 'true' && inputs.test == 'true'
      shell: bash
      env:
        CI: true
      run: yarn test:ci

    - name: 📊 Code coverage
      if: inputs.checks == 'true' && inputs.coverage == 'true'
      uses: codecov/codecov-action@v2.1.0
