name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        with:
          build: false
          checks: true
          # FIXME: https://github.com/actions/runner/issues/834 (code-ql: false)
          test: false
          coverage: false

  publish:
    needs: continuous-integration
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v2

      - name: 🔖 Configure publish
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          mkdir -p /tmp/publish

      - name: 📖 Generate README
        uses: bitflight-devops/github-action-readme-generator@v1.0.12a
      - run: cp README.md /tmp/publish/index.md

      - name: 🌐 Publish Github pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/publish
          enable_jekyll: true
