name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: ./
        with:
          checkout: false
          build: false
          checks: true
          code-ql: false
          test: false
          coverage: false

  publish:
    needs: continuous-integration
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          build: false
          checkout: '{ "token": "${{ secrets.GH_PRIVATE_ACCESS_TOKEN }}" }'

      - name: 🔖 Configure publish
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "${{ github.actor }}"

      - name: 📖 Generate README
        uses: bitflight-devops/github-action-readme-generator@v1.0.12a

      - run: |
          echo `git add -A && git commit -m "chore: prepare release"`
          git push --follow-tags origin ${{ github.event.repository.default_branch }}

          mkdir -p /tmp/publish
          echo "theme: jekyll-theme-cayman" > /tmp/publish/_config.yml
          cp README.md /tmp/publish/index.md

      - name: 🌐 Publish Github pages
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          enable_jekyll: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /tmp/publish
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
